name: thelper
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - ddt
  - gitdb
  - gitpython
  - h5py
  - hdf5plugin
  - lz4
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pip
  - pytorch<1.3
  - pyyaml
  - scikit-learn
  - six
  - torchvision
  - tqdm
  - pip:
    - opencv-python
    - tensorboardX
